### PR TITLE
Fix type instabilities of SimplexBijector

### PR DESCRIPTION
**Pull request by devmotion**
Fixes type instabilities discovered in https://github.com/TuringLang/Turing.jl/issues/1276.

### CODE REVIEW

**Comment by torfjelde** [comment]
I'll review, but quick quesh first: is there a reason why you re-introduced the `Val`? I don't think that's necessary here; at least when I experimented, it wasn't.

**Comment by devmotion** [comment]
I could not obtain type stability without it. IMO this seems reasonable since it is not possible to infer the type, or rather the type parameter `proj`, of `SimplexBijector` from a boolean value `proj`.

**Comment by torfjelde** [comment]
For the case when `proj` is a runtime parameter you mean, or nah? It is inferrable if you do `SimplexBijector{true}()`.

**Comment by devmotion** [comment]
Sure, you can hardcode it for the default version with `true` - but the three argument version, with `true` or `false`, is still type unstable.

**Comment by devmotion** [comment]
BTW also with your suggestion in https://github.com/TuringLang/Turing.jl/issues/1276#issuecomment-813074909 `invlink(d, x)` is still type unstable. It seems you accidentally checked `link(d, x)` instead?

**Comment by torfjelde** [comment]
Haha, yeah you're right! Sorry about that. I think I was just cycling through my command history to get the function call and seems like I was a bit too quick.

But regarding the 3-argument version. The reason why we replaced `Val` with `proj` was because when you construct the bijector in a different scope than `Main`, you'll have to hardcode `proj` to get type-stability no matter if we're using `Val` or not. And if you hardcode, even when not using `Val`, you should get type stability due to constant propogation.

Thouhgh in the light of the stuff we saw in the DPPL PR, I'm not so certain about that anymore:) And it seems like even something as simple as

```julia
f(d, x) = Bijectors.invlink(d, x, true)
```

fails :confused:

So I guess I'm in favour of adding back the `Val`.

**Review by torfjelde — APPROVED** [review]
LGTM!

But is this considered a breaking change? Should we bump the minor version or? (Also can you bump the version?:) )

**Comment by devmotion** [comment]
Yes, IMO this is a breaking change.

**Pull request merged**
