### PR TITLE
Fix import of ReverseDiff

### PR DESCRIPTION
**Pull request by devmotion**
This PR fixes errors such as
```julia
┌ Warning: Error requiring ReverseDiff from Bijectors:
│ LoadError: ArgumentError: Package Bijectors does not have ReverseDiff in its dependencies:
│ - If you have Bijectors checked out for development and have
│   added ReverseDiff as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Bijectors
```
when loading, e.g., Turing.

### CODE REVIEW

**Comment by devmotion** [comment]
It seems the Zygote tests took too long to run. However, Zygote support and integration is completely unrelated to this PR. My general impression is that it takes a lot of time to run the CI tests - I'm not sure if splitting some test sets could be helpful?

**Comment by yebai** [comment]
@devmotion Would you like to fix the git conflicts before merging?

**Comment by devmotion** [comment]
Sure, I'll fix the conflicts. It seems @mohamed82008 has already opened and merged another PR to address the problem, but it seems there are still some accesses of ReverseDiff at the top of the file - IMO one should add a `import .ReverseDiff` statement at the top (and probably move the other imports there as well).

**Comment by devmotion** [comment]
See: https://github.com/TuringLang/Bijectors.jl/pull/97

**Pull request merged**
