### PR TITLE
Re-add expansion of `Enzyme.@import_{r,f}rule` to BijectorsEnzymeExt

### PR DESCRIPTION
**Pull request by penelopeysm**
Since Enzyme now works, but Julia hasn't been fixed, this re-enables the extension. See https://github.com/TuringLang/Bijectors.jl/issues/339#issuecomment-2460682359.

In the process, it aso re-enables tests that are no longer broken.

### CODE REVIEW

**Review by devmotion — COMMENTED** [review]
IMO that's incomprehensible. What's the reason for not just implementing the forward and reverse-mode Enzyme rules? The function and the partial derivatives are very simple, and a direct implementation is likely faster and avoids unnecessary overhead. As also mentioned in the docstrings of `@import_rrule` and `@import_frule`, these macros most likely do not give you the most performant implementation (and they might lead to broken rules but I assume it's fine in this simple case here).

**Comment by devmotion** [comment]
> it's only really intended as a stopgap measure until 1.11.2 is released, at which point we can get rid of all of this.

My point is that even when the Pkg issues are fixed, I think ideally you would use `@import_frule` neither `@import_rrule`.

**Comment by penelopeysm** [comment]
I will pass that on :)

**Comment by penelopeysm** [comment]
But maybe @willtebbutt or @mhauru one of you are better placed to do this (at some point in time)?

**Comment by penelopeysm** [comment]
Is it possible to merge this first and keep track of the proper rule-writing in another issue?

Right now we have a missing rule and that will make things break.

**Comment by devmotion** [comment]
> @devmotion, since you wrote the ChainRulesCore [rule](https://github.com/JuliaMath/Roots.jl/blob/master/ext/RootsChainRulesCoreExt.jl) for Roots.jl, would you be happy to do the same for Enzyme, or coach @mhauru to do it?

Well, one could do that. But that's again too generic for Bijectors IMO. The only interest here is one specific function, so only a rule for this specific function is needed. I assume generally performance of such a specific rule will be better than performance of generic Roots.jl rules.

I should have some time this evening, I'll open a draft PR and see how far I can get.

**Pull request closed without merging**
