### PR TITLE
Use NonlinearSolve instead of Roots

### PR DESCRIPTION
**Pull request by devmotion**
Motivated by https://github.com/TuringLang/Bijectors.jl/issues/154, this PR replaces Roots with NonlinearSolve which is the root solving package that replaced Roots in the SciML ecosystem. NonlinearSolve states in its README
> Performance is key: the current methods are made to be highly performant on scalar and statically sized small problems.

and

> The current algorithms should support automatic differentiation, though improved adjoint overloads are planned to be added in the current update.

### CODE REVIEW

**Review by cpfiffer — APPROVED** [review]
Looks good to me, though maybe @torfjelde has opinions on it. I also agree with adding this instead of Roots -- seems they have a much more AD-friendly perspective.

**Comment by cpfiffer** [comment]
Hm, seems like a fairly big issue -- my imagining is that thunks require some large-ish structural modficiations?

**Comment by devmotion** [comment]
Actually I'm not sure, it could be that it is sufficient to just unthunk always when applying the results of the pullback (if it's not a thunk, unthunking would just be a no-op). But I'm not too familiar with the Zygote internals and hence I created the issue.

If we don't want to wait, my suggestion would be to just mark the failing tests as broken in DistributionsAD and Bijectors and open an issue, so we don't forget about it. IIRC it affects Skellam, Pareto, and NormalInverseGaussian with Zygote.

**Comment by cpfiffer** [comment]
I think that'd be fine. IMO Zygote isn't really the priority AD backend anyway so I don't think we should wait on them.

**Review by torfjelde — APPROVED** [review]
Looks good! And I'm fine with the error in Zygote.jl if we make a corresponding issue so as to remind ourselves that this needs to be updated when we have a fix.

**Comment by devmotion** [comment]
OK, I will update the tests in https://github.com/TuringLang/DistributionsAD.jl/pull/143 and then apply the same changes to the Bijectors tests which take more time to run.

**Pull request merged**
